name: Jest
on:
  schedule:
    - cron: '0 2 * * *'
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Clear npm cache
        run: npm cache clean -f

      # Install required deps for action
      - name: Install Dependencies
        run: npm install

      # Finally, run our tests
      - name: Run the tests
        run: npm test